credentials:
  usernames:
    oracle:
      email: oracle9@gmail.com
      name: oracle
      password: $2b$12$bf5aiAtmyBQbd9OAyqpM5eauak4NBzDJmuPeVG7N0FJC6qUORKMrq
    yk:
      email: yk9@gmail.com
      name: yk
      password: $2b$12$gyj6AxA40dNL6iNjqht1O.8/e/KpU20yfPZ4BgcITs2yVDiD3SQjy
cookie:
  expiry_days: 30
  key: 71f464977314272e300e1d96c517898c60aa25ccb4b4d67f
  name: mlberry
